### ISSUE TITLE
Looking for help/feedback?

### ISSUE THREAD

**Issue by AlexanderCecile** [T145/anipop#1]
Hello!

I was wondering if you are still looking for help and/or feedback on this project, following your [post on Code Review](https://codereview.stackexchange.com/questions/231064/anipop-the-anime-downloader). There were a few things I never brought up, and recently discovered that I had actually written some code but forgot to share it at the time. I made a [new room](https://chat.stackexchange.com/rooms/108162/room-for-amc-and-t145) on the Stack Exchange Chat, although I'm not sure if you get notified of that.

**Comment by T145** [comment]
Sure, anything helps. Feel free to post some stuff here, fork the project, etc.

**Comment by T145** [comment]
I sent a message to that chat room containing a link to my Discord

**Comment by T145** [comment]
Here's a permalink: https://discord.gg/Bc7naB6

**Comment by AlexanderCecile** [comment]
Wonderful, I joined the server and sent you an invite.
